### ISSUE TITLE
Remove the requirements for adding an additional app key in case a user is logging in with the account that was previously used

### ISSUE THREAD

**Issue by djsatok** [near/rainbow-bridge-frontend#153]
At the moment every time when a user switches NEAR account he asked to add the app key in the NEAR Wallet

**Comment by paouvrard** [comment]
App keys can totally be removed since we are using wallet redirects to sign all transactions: this is now possible with naj v0.39.0
If the user clicks `Disconnect` then the next time the user connects, the wallet redirect should still happen to let the user select the account to connect (this is not the case in Metakask as it lets you change accounts from the connected wallet)
