### ISSUE TITLE
`mint` is not available if first `mint` action is not finalized

### ISSUE THREAD

**Issue by mfornet** [near/rainbow-bridge-frontend#154]
When I call mint, I got redirected to wallet to approve the tx. If I close that tab without  approving (or canceling) the tx. The UI stays in a state where it is waiting for approval, and I can’t call mint again from the UI.

**Comment by paouvrard** [comment]
Nice one!
This fixes the issue: https://github.com/near/rainbow-bridge-client/pull/13

The problem also happens if user clicks go back from the wallet -> https://github.com/near/rainbow-bridge-frontend/pull/156

Note: if the transaction is broadcasted but the callback wasn't done (user closes tab, clicks go back ... after the sign and broadcast) then the dapp doesn't know if a transaction was made, so that transfer should be recovered.
![image](https://user-images.githubusercontent.com/29397451/111865528-f9017500-89aa-11eb-975a-9b68dd5ea31e.png)
