### ISSUE TITLE
Job Stories: Rainbow Bridge v0

### ISSUE THREAD

**Issue by corwinharrell** [near/rainbow-bridge-frontend#42]
When designing an MVP, it's beneficial to lay out user stories at the outset of a project as a means to comprehensively survey the various user tasks and motivations.

In contrast to user stories, I actually favor [Job Stories](https://thoughtbot.com/blog/converting-to-jobs-stories) to fill this role. Job stories tend to be less prescriptive of user actions or solutions, and tend to provide more information about a user's _context_ and _motivations_, which help to frame the problems we're solving more effectively.

The job story format looks like the following:

> When I [situation], I want to [motivation] so I can [outcome/benefit].

In preparation for designing the front-end for the rainbow bridge, let's go through and define our job stories for our v0, making sure to focus not on prescribing specific solutions (eg "we need a button for..."), but rather our users' context, motivations, and outcomes. This list should be focused only on the stories we will be solving for for the MVP. These stories will be used to set and maintain context for decision making during the UX and UI design process.

## Job Stories
A few examples to start:

~- [x] When I _first set out_ to transfer tokens from my Ethereum wallet to my NEAR wallet, I want to know which ERC20 tokens are available to transfer, so I can ensure I have the correct ERC20 tokens available in my Ethereum wallet.~

- [x] After I initiate a transfer, I want to follow the progress of my transfer every step of the way, so that I can stay informed about the state of the transfer and any significant events that occur during processing.

~- [ ] When a transfer I initiated is successful, I want to be notified about its completion, so I know when my transferred tokens are available to use.~

- [ ] When a transfer I initiated encounters a problem, I want to be notified of and be given context about the issue, so I can make an informed decision about what I might need do to resolve it.

**Comment by chadoh** [comment]
* When I learn about the Rainbow Bridge, I want to play with it so I can understand it better

* When I first set out to transfer tokens from my Ethereum wallet to my NEAR wallet, I want to ~know which ERC20 tokens are available to transfer~ see a list of featured ERC20 tokens, so I can easily send popular tokens.

* [pro feature; could only use URL at launch] When I want to send a token that isn't in the featured list, I can figure out how to enter my token's contract address, so I can send tokens that aren't in the featured list.

  * When I enter a non-standard ERC20 token that isn't supported by the connector, I see a warning message and sending is disabled, so I don't send known-unsupported tokens. [this will have to function as a blacklist, and could obviously miss unknown edge cases]

* After I initiate a transfer, I want to follow the progress of my transfer every step of the way, so that I can stay informed about the state of the transfer and any significant events that occur during processing.

* When a transfer I initiated is ~successful, I want to be notified about its completion, so I know when my transferred tokens are available to use.~ ready to complete, I want to be brought back to this tab so I can sign the final transaction of the process and see my completed transfer.

* When a transfer I initiated encounters a problem, I want to be notified of and be given context about the issue, so I can make an informed decision about what I might need do to resolve it.

**Comment by djsatok** [comment]
> [pro feature; could only use URL at launch] When I want to send a token that isn't in the featured list, I can figure out how to enter my token's contract address, so I can send tokens that aren't in the featured list.

I suggest to change this into:
- When I want to send a token that isn't in the featured list, I can specify the token in the meaningful way (Token's contract address? Something different?), so I can send tokens that aren't in the featured list
- When I specified a contract address of the token that is not in a featured list, I can see additional transaction costs, so I can understand whether this transaction is too expensive to me or not (see below)

I don't think this is a `pro` feature. The `TokenFactory` should automatically detect whether the ERC-20 token was not bridged yet and deploy a corresponding NEP-21 contract. Same should be true for the NEP-21 transfers to Ethereum.

Also I would add:
- When I want to transfer tokens, I can see the estimation of transaction fees, so I can understand the cost of the transfer
- When I want to transfer tokens, I can see a `low amount` warning, so I can understand that my wallets won't be able to cover transaction costs (including NEAR wallet that should persist some amount for paying for the storage)
- When I want to use a bridge, I can see it's health status, so I can understand whether the bridge is operational or not
- When I want to use a bridge, I can see the login status, so I can understand whether I can actually do transfers or not
- When I prepared a transfer, just before I initiate it, I can see the steps that I would need to do down the road with their restrictions and approximate timings, so I can plan my other activities and decide whether it's convenient time now to do it


Not necessary, but this will conclude the user experience:
- When I want to work with the bridge, I can see my portfolio of tokens on both Ethereum and NEAR, so I can quickly understand where my liquidity is located

**Comment by chadoh** [comment]
> > [pro feature; could only use URL at launch] When I want to send a token that isn't in the featured list, I can figure out how to enter my token's contract address, so I can send tokens that aren't in the featured list.
> 
> I suggest to change this into:
> 
> * When I want to send a token that isn't in the featured list, I can specify the token in the meaningful way (Token's contract address? Something different?), so I can send tokens that aren't in the featured list
> * When I specified a contract address of the token that is not in a featured list, I can see additional transaction costs, so I can understand whether this transaction is too expensive to me or not (see below)
> 
> I don't think this is a `pro` feature. The `TokenFactory` should automatically detect whether the ERC-20 token was not bridged yet and deploy a corresponding NEP-21 contract. Same should be true for the NEP-21 transfers to Ethereum.

I think entering a custom ERC20 address is a pro feature, meaning that I think it would be acceptable for it to require entering this ERC20 address via the URL bar. This is how it works currently; try it out at near.github.io/rainbow-bridge-frontend (you can find Rinkeby ERC20s at https://rinkeby.etherscan.io/tokentxns)

However, once you enter a custom address, I agree that the UI needs to show you if this token already has a connector deployed. It already does this also, though the UI should probably be cleaned up. 

My nested job story, about unsupported ERC20s, is about custom ERC20s that would not work as expected using the current connector, because they do unexpected things. We need to deal with this, too.

So my updated job stories would be:

* [pro feature; could only use URL at launch] When I want to send a token that isn't in the featured list, I can figure out how to enter my token's contract address, so I can send tokens that aren't in the featured list.

  * When I enter an ERC20 token that has not yet been bridged, I see a message explaining the situation which gives me the option of deploying the BridgeToken contract, so I can deploy this BridgeToken if I have the funds and desire to do so

  * When I enter a non-standard ERC20 token that isn't supported by the connector, I see a warning message and sending is disabled, so I don't send known-unsupported tokens. [this will have to function as a blacklist, and could obviously miss unknown edge cases]

**Comment by djsatok** [comment]
This is finished
