### ISSUE TITLE
Critical Path: Rainbow Bridge v0

### ISSUE THREAD

**Issue by corwinharrell** [near/rainbow-bridge-frontend#43]
While Job Stories (being defined for this project in #42) are useful for collecting a list of the granular motivations and decisions that users will be making as they interact with our product, it's also important to keep in mind the higher-level user journey.

Unlike job stories, a critical path can be illustrated in a number of ways (text, flowcharts, other diagrams). It's up to the author. The ultimate goal is to illustrated a **_single_** primary/critical path (ignoring major divergences) that a user will take from the point at which they enter the application, to the point at which they have achieved their primary goal, and all the steps in between (in our case: from sign in to the successful exchange of a certain amount of a single ERC20 to its NEAR equivalent).

As a design reference for how we envision a user traveling between points A > B > C, let's define the _Critical Path_ that a user is most likely to traverse during their initial encounter with our MVP.

**Comment by chadoh** [comment]
1. Someone visits Bridge landing page, with curiosity about NEAR and the Rainbow Bridge but not necessarily a deep understanding
2. They learn about Bridge and get prompted to sign in with Ethereum + NEAR to try transferring some assets to NEAR
3. They sign in with both Ethereum (MetaMask) and NEAR
4. They select an asset to transfer (maybe DAI is pre-selected?)
5. They enter an amount to transfer and initiate the transfer
6. As is customary for ERC20 transactions, they are required to sign twice, once to allow the Token Locker contract to move a certain amount of tokens for them, once to actually transfer these tokens to the Token Locker contract (if we want to follow the pattern used by Uniswap and others, we can have them allow Token Locker to transfer _unlimited_ funds for them, so they only have to sign once on subsequent transfers, and therefore have lower transaction fees but require higher trust in Token Locker contract)
7. They wait some time, and see the status of their tokens being sent across the bridge. They feel confident during this journey. Maybe they have additional learning material presented to them during this wait.
8. Once enough blocks have made it into the EthOnNearClient (the "10/10 blocks synced" point), wrapped tokens are minted on the NEAR side (we may want to call this "completing the transfer" instead of "minting" in the UI). This redirects to NEAR Wallet for a signature from them, so maybe it's best to send a system notification to get them back to this page if they switched away during the wait, because the minting can time out (but it can also be retried if it times out, so notification might be optional).
9. They land back at Rainbow Bridge, and see both a success message and their incremented balance on the NEAR side for this token

**Comment by djsatok** [comment]
Great job, @chadoh! This is exactly the critical path that we expect. Absolutely the same stands for the transfers back with the difference that a NEAR -> Ethereum transfers take much longer (approx. 4 hours). We should count for this in the point 7.

**Comment by djsatok** [comment]
This is finished
