### ISSUE TITLE
Issue with erc20 token approvals

### ISSUE THREAD

**Issue by paouvrard** [near/rainbow-bridge-frontend#97]
Currently for locking a token, it's allowance needs to be set so that the lock contract can pull the tokens.
This allowance is currently set by calling erc20Contract.methods.approve().
If a user initiates two eth -> near transfers, then the allowance will not have been increased by the 2nd transfer (because approve only sets approval and simply overrides the previous approval) and the erc20Contract.methods.lock() will fail.

Possible solutions:
- Increase the allowance instead of setting it. But some erc20 tokens implement increaseAllowance() and others increaseApproval().
- Prevent the user from initiating a transfer while the previous one is not locked.
- Give the maximum allowance to the lock contract.

**Comment by djsatok** [comment]
Great finding @paouvrard!

I think we should solve it with the second option, though it creates a limitation to the user behaviour.

There're two reasons for doing that:
1. A user may be confused with approving a `X` tokens transfer and then immediately approving a `X+Y` tokens transfer. From the point of view of many users this might seem like a contract tries to get the access to the additional funds. There's no simple way how to solve it without displaying lots of info on how allowances are working.
2. Normally a user should not a second transfer while the first one is in the execution. The main reason for multiple transfers is the reduction of losses due to an error (contract execution, copying the addresses, etc.). But this implies that a user should wait until the first transfer is finished, then he would start the second one.

However, let's consider adding the maximum allowance option in the future, because this option helps to decrease the cost of a Ethereum->NEAR transfer by >50% (see [approve tx](https://ropsten.etherscan.io/tx/0x512371d971f01e685f33b5467ca90ecdf46006ea67678ab038424386df73cd2e) and [locking tx](https://ropsten.etherscan.io/tx/0x41c00b577fa26423085015f96f82210c2cf41072893f94c27b4bffa95f0fe630)).

**Comment by paouvrard** [comment]
Fixed here: https://github.com/near/rainbow-bridge-client/pull/3
![image](https://user-images.githubusercontent.com/29397451/109917535-dc9de100-7cf8-11eb-8b33-7d7fe0ce4911.png)
